import 'package:movie_booking/data/vos/actor_vo.dart';
import 'package:movie_booking/data/vos/movie_vo.dart';

List<MovieVO> getMockMovieForTest() {
  return [
    MovieVO(
      false,
      "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
      [16, 10751, 35, 14],
      508947,
      "en",
      "Turning Red",
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      5126.644,
      "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      "2022-03-01",
      "Turning Red",
      false,
      7.5,
      1450,
      null,
      200000000,
      null,
      "https://www.warnerbros.com/movies/wonder-woman-1984",
      null,
      null,
      null,
      165160005,
      151,
      null,
      "Released",
      "A new era of wonder begins.",
      true,
      false,
    ),
    MovieVO(
      false,
      "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
      [16, 10751, 35, 14],
      508947,
      "en",
      "Turning Red",
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      5126.644,
      "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      "2022-03-01",
      "Turning Red",
      false,
      7.5,
      1450,
      null,
      200000000,
      null,
      "https://www.warnerbros.com/movies/wonder-woman-1984",
      null,
      null,
      null,
      165160005,
      151,
      null,
      "Released",
      "A new era of wonder begins.",
      false,
      true,
    ),
    MovieVO(
      false,
      "/yzpCv8CCWondN7O5au1KGiqnC3A.jpg",
      [16, 10751, 35, 14],
      414906,
      "en",
      "Turning Red",
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      5126.644,
      "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      "2022-03-01",
      "The Batman",
      false,
      7.5,
      1450,
      null,
      200000000,
      null,
      "https://www.warnerbros.com/movies/wonder-woman-1984",
      null,
      null,
      null,
      165160005,
      151,
      null,
      "Released",
      "A new era of wonder begins.",
      true,
      false,
    ),
  ];
}

List<ActorVO> getMockActorForTest() {
  return [
    ActorVO(
      false,
      1,
      224513,
      [],
      "Acting",
      "Ana de Armas",
      107.821,
      "/14uxt0jH28J9zn4vNQNTae3Bmr7.jpg",
      null,
      null,
      null,
      null,
      null,
    ),
    ActorVO(
      false,
      2,
      1136406,
      [],
      "Acting",
      "Tom Holland",
      94.667,
      "/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg",
      null,
      null,
      null,
      null,
      null,
    ),
    ActorVO(
      false,
      2,
      3030319,
      [],
      "Crew",
      "Mile Phakphum Romsaithong",
      92.579,
      "/CJNW34J8v1TZbD1jrloqFAMGKt.jpg",
      null,
      null,
      null,
      null,
      null,
    ),
  ];
}
